Henxun.Cms.Admin/Controllers/ManagerController.cs
using AutoMapper;
using Henxun.Cms.Core.Helper;
using Henxun.Cms.IServices;
using Henxun.Cms.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Henxun.Cms.Admin.Controllers
{
    [Authorize(Roles = "1")]
    public class ManagerController : Controller
    {
        private readonly IManagerService managerService;
        private readonly IManagerRoleService managerRoleService;
        private readonly IHttpContextAccessor httpContextAccessor;

        private IEnumerable<SelectListItem> Roles => managerRoleService.GetListByCondition(new ManagerRoleRequestModel()).Select(s=>new SelectListItem { Text = s.RoleName, Value = s.Id.ToString()});

        public ManagerController(IManagerService managerService,IManagerRoleService managerRoleService,IHttpContextAccessor httpContextAccessor)
        {
            this.managerService = managerService;
            this.managerRoleService = managerRoleService;
            this.httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Get(string key,int page = 1,int limit = 10)
        {
            var data = await managerService.LoadDataAsync(new ViewModels.ManagerRequestModel() { Key = key, Page = page, Limit = limit});
            if (data.code == 200)
                return new JsonResult(new
                {
                    code = "0",
                    msg = "",
                    count = data.count,
                    data = data.data
                });
            else
                return new JsonResult(new
                {
                    code = "-1",
                    msg = "失败",
                });
        }

        [Authorize(Roles = "1")]
        public IActionResult Add()
        {
            ViewBag.RoleList = Roles;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Post(ManagerAddOrModifyModel model)
        {
            var result = await managerService.AddOrModifyAsync(model);
            return new JsonResult(result);
        }

        public IActionResult Edit(string data)
        {
            string json = System.Web.HttpUtility.HtmlDecode(data);
            var model = JsonConvert.DeserializeObject<ManagerAddOrModifyModel>(json);
            ViewBag.RoleList = Roles;
            return View(model);
        }

        public async Task<IActionResult> Delete(int[] ids)
        {
            var res = await managerService.DeleteIdsAsync(ids);
            return new JsonResult(res);
        }

        public async Task<IActionResult> ChangeLockStatus(int id, bool status)
        {
            var res = await managerService.ChangeLockStatusAsync(new ChangeStatusModel { Id= id,Status = status});
            return new JsonResult(res);
        }

        public IActionResult ChangePassword()
        {
            ViewData["NickName"] = User.Claims.FirstOrDefault(x => x.Type == "NickName")?.Value;
            ViewData["Id"] = User.Claims.FirstOrDefault(x => x.Type == "Id")?.Value;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/Manager/ChangePassword")]
        public async Task<string> ChangePasswordAsync([FromForm] ChangePasswordModel item)
        {
            var result = new BaseResult();
            if (!ModelState.IsValid)
            {
                result.ResultCode = ResultCodeAddMsgKeys.CommonModelStateInvalidCode;
                result.ResultMsg = ResultCodeAddMsgKeys.CommonModelStateInvalidMsg;
            }
            else
            {
                result = await managerService.ChangePasswordAsync(item);
            }
            return JsonHelper.ObjectToJSON(result);
        }

        public async Task<IActionResult> Detail()
        {
            var id = User.FindFirst("Id");
            if(null == id)
            {
                return RedirectToAction("SignOut", "Account");
            }
            var model = await managerService.GetManagerContainRoleNameByIdAsync(int.Parse(id.Value));
            if(null == model)
            {
                return RedirectToAction("SignOut", "Account");
            }
            model.Avatar = model.Avatar ?? "/images/userface1.jpg";
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/Manager/ManagerInfo")]
        public async Task<string> ManagerInfoAsync([FromForm] ChangeInfoModel item)
        {

            var result = new BaseResult();
            if (ModelState.IsValid)
            {
                item.ModifyManagerId = int.Parse(User.Claims.FirstOrDefault(x => x.Type == "Id")?.Value);
                item.ModifyTime = DateTime.Now;
                result = await managerService.UpdateManagerInfoAsync(item);
                httpContextAccessor.HttpContext.Session.SetString("NickName", item.NickName ?? "匿名");
                httpContextAccessor.HttpContext.Session.SetString("Email", item.Email ?? "");
                httpContextAccessor.HttpContext.Session.SetString("Avatar", item.Avatar ?? "/images/userface1.jpg");
                httpContextAccessor.HttpContext.Session.SetString("Mobile", item.Mobile ?? "");
            }
            else
            {
                result.ResultCode = ResultCodeAddMsgKeys.CommonModelStateInvalidCode;
                result.ResultMsg = ResultCodeAddMsgKeys.CommonModelStateInvalidMsg;
            }

            return JsonHelper.ObjectToJSON(result);
        }
    }
}

Henxun.Cms.Admin/Views/Manager/Add.cshtml
@using Henxun.Cms.ViewModels
@model Henxun.Cms.ViewModels.ManagerAddOrModifyModel
@{
    Layout = null;
    var roleList = ViewBag.RoleList as IEnumerable<SelectListItem>;
}
<html>
<head>
    <link rel="stylesheet" href="~/layui/css/layui.css" media="all" />
    <link rel="stylesheet" href="~/css/public.css" media="all" />

    <style>
    </style>
</head>
<body style="padding:10px">

    <form id="add" class="layui-form">
        @Html.AntiForgeryToken()
        <div class="layui-form-item">
            <label for="username" class="layui-form-label">用户名</label>
            <div class="layui-input-block">
                <input id="username" name="userName" type="text" class="layui-input" lay-verify="required|userName" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="roleId" class="layui-form-label">所属角色</label>
            <div class="layui-input-block">
                <select id="roleId" name="roleId" lay-filter="role">
                    @foreach (var item in roleList)
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label for="nickName" class="layui-form-label">用户昵称</label>
            <div class="layui-input-block">
                <input id="nickName" name="nickName" class="layui-input" type="text" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="email" class="layui-form-label">邮箱</label>
            <div class="layui-input-block">
                <input id="email" type="email" name="email" class="layui-input" lay-verify="required|email" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="mobile" class="layui-form-label">电话</label>
            <div class="layui-input-block">
                <input id="mobile" name="mobile" type="tel" class="layui-input" lay-verify="required|phone" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="remark" class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <textarea id="remark" name="remark" placeholder="请输入内容" class="layui-textarea"></textarea>
            </div>
        </div>
        <div class="layui-form-item layui-right">
            <button class="layui-btn" lay-submit lay-filter="confirm">确定</button>
        </div>
    </form>
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <script type="text/javascript" src="~/js/submit.js?_=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>
    <script type="text/javascript" src="~/js/verify.js?_=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>
    <script>
        registerSubmit('Manager')
    </script>
</body>
</html>

Henxun.Cms.Admin/Views/Manager/AddUser.cshtml
@using Henxun.Cms.ViewModels
@model Henxun.Cms.ViewModels.ManagerAddOrModifyModel
@{
    Layout = null;
    var roleList = ViewBag.RoleList as IEnumerable<SelectListItem>;
}
<html>
<head>
    <link rel="stylesheet" href="~/layui/css/layui.css" media="all" />
    <link rel="stylesheet" href="~/css/public.css" media="all" />
</head>
<body style="padding:10px">
    @using (Html.BeginForm("AddUserByModel", "Manager", FormMethod.Post, new { Id = "addUser", Class = "layui-form" }))
    {
        @Html.AntiForgeryToken()
        <div class="layui-form-item">
            @Html.LabelFor(m => m.UserName, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.UserName, new { Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.RoleId, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.DropDownListFor(m => m.RoleId, roleList)
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.NickName, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.NickName, new { Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.Email, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.Email, new { Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.Mobile, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.Mobile, new { @type = "number", Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.Remark, new { @class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextAreaFor(m => m.Remark, new { @placeholder = "请输入内容", @class = "layui-textarea" })
            </div>
        </div>
        <div class="layui-form-item layui-right">
            <button class="layui-btn" lay-submit lay-filter="addUser">确定</button>
        </div>
    }
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <script>
        layui.use('form', function () {
            var form = layui.form;
            form.on('submit(addUser)', function (data) {
                console.info(data);
            })
        })
    </script>
</body>
</html>

Henxun.Cms.Admin/Views/Manager/ChangePassword.cshtml
@{ ViewData["Title"] = "密码修改"; }

<form class="layui-form layui-row changePwd">
    @Html.AntiForgeryToken()
    @Html.Hidden("Id", @ViewData["Id"])
    <div class="layui-col-xs12 layui-col-sm6 layui-col-md6">
        <div class="layui-input-block layui-red pwdTips">需先输入旧密码，然后新密码必须两次输入一致才能提交</div>
        <div class="layui-form-item">
            <label class="layui-form-label">用户名</label>
            <div class="layui-input-block">
                <input type="text" value="@ViewData["NickName"]" disabled class="layui-input layui-disabled">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">旧密码</label>
            <div class="layui-input-block">
                <input type="password" name="OldPassword" id="OldPassword" placeholder="请输入旧密码" lay-verify="required|oldPwd" class="layui-input pwd">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">新密码</label>
            <div class="layui-input-block">
                <input type="password" name="NewPassword" id="NewPassword" placeholder="请输入新密码" lay-verify="required|newPwd" class="layui-input pwd">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">确认密码</label>
            <div class="layui-input-block">
                <input type="password" name="NewPasswordRe" id="NewPasswordRe" placeholder="请确认密码" lay-verify="required|confirmPwd" class="layui-input pwd">
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit="" lay-filter="changePwd">立即修改</button>
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
            </div>
        </div>
    </div>
</form>
@section Scripts{
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <script type="text/javascript" src="~/js/manager/changepassword.js?_=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>
}

Henxun.Cms.Admin/Views/Manager/Detail.cshtml
@model Henxun.Cms.Models.Manager
@{ ViewData["Title"] = "个人信息"; }
<form class="layui-form layui-row">
    <div class="layui-col-md3 layui-col-xs12 user_right">
        <div class="layui-upload-list">
            <img src="@Model.Avatar" class="layui-upload-img layui-circle userFaceBtn userAvatar" id="userFace">
        </div>
        <button type="button" class="layui-btn layui-btn-primary userFaceBtn"><i class="layui-icon">&#xe67c;</i> 掐指一算，我要换一个头像了</button>
        @Html.Hidden("Avatar", Model.Avatar)
        @Html.Hidden("Id", Model.Id)
        @Html.AntiForgeryToken()
    </div>
    <div class="layui-col-md6 layui-col-xs12">
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">用户账号</label>
            <div class="layui-input-block">
                <input type="text" value="@Model.UserName" name="UserName" ,id="UserName" disabled class="layui-input layui-disabled">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">用户角色</label>
            <div class="layui-input-block">
                <input type="text" value="@Model.RoleName" name="RoleName" id="RoleName" disabled class="layui-input layui-disabled">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">真实姓名</label>
            <div class="layui-input-block">
                <input type="text" value="@Model.NickName" name="NickName" id="NickName" placeholder="请输入真实姓名" lay-verify="required" class="layui-input realName">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">手机号码</label>
            <div class="layui-input-block">
                <input type="tel" value="@Model.Mobile" name="Mobile" id="Mobile" placeholder="请输入手机号码" lay-verify="phone" class="layui-input userPhone">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">电子邮箱</label>
            <div class="layui-input-block">
                <input type="tel" value="@Model.Email" name="Email" id="Email" placeholder="请输入电子邮箱" lay-verify="email" class="layui-input userPhone">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <textarea placeholder="请输入内容" name="Remark" id="Remark" class="layui-textarea myself">@Model.Remark</textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit="" lay-filter="changeManager">立即提交</button>
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
            </div>
        </div>
    </div>
</form>
@section Scripts{
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <script type="text/javascript" src="~/js/manager/managerInfo.js?_=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>
}

Henxun.Cms.Admin/Views/Manager/Edit.cshtml
       @addTagHelper *,Henxun.Cms.Admin
@model Henxun.Cms.ViewModels.ManagerAddOrModifyModel
@{
    Layout = null;
    var roleList = ViewBag.RoleList as IEnumerable<SelectListItem>;
}
<html>
<head>
    <link rel="stylesheet" href="~/layui/css/layui.css" media="all" />
    <link rel="stylesheet" href="~/css/public.css" media="all" />
</head>
<body style="padding:10px">
    <form id="edit" class="layui-form">
        @Html.AntiForgeryToken()
        <div class="layui-form-item layui-hide">
            <label for="id" class="layui-form-label"></label>
            <div class="layui-input-block">
                <input id="id" name="id" type="number" class="layui-input" value="@ViewData.Model.Id" lay-verify="required" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="userName" class="layui-form-label">用户名</label>
            <div class="layui-input-block">
                <input id="userName" name="userName" type="text" class="layui-input" value="@ViewData.Model.UserName" lay-verify="required|userName" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="roleId" class="layui-form-label">所属角色</label>
            <div class="layui-input-block">
                <select id="roleId" name="roleId" lay-filter="role">
                    @foreach (var item in roleList)
                    {
                        @if (item.Value.Equals(ViewData.Model.RoleId.ToString()))
                        {
                            <option value="@item.Value" selected>@item.Text</option>
                        }
                        else
                        {
                            <option value="@item.Value">@item.Text</option>
                        }

                    }
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <label for="nickName" class="layui-form-label">用户昵称</label>
            <div class="layui-input-block">
                <input id="nickName" name="nickName" class="layui-input" type="text" value="@ViewData.Model.NickName" lay-verify="required" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="email" class="layui-form-label">邮箱</label>
            <div class="layui-input-block">
                <input id="email" type="email" name="email" class="layui-input" lay-verify="required|email" value="@ViewData.Model.Email" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="mobile" class="layui-form-label">电话</label>
            <div class="layui-input-block">
                <input id="mobile" name="mobile" type="tel" class="layui-input" lay-verify="required|phone" value="@ViewData.Model.Mobile" />
            </div>
        </div>
        <div class="layui-form-item">
            <label for="isLock" class="layui-form-label">锁定</label>
            <cl-switch asp-for="IsLock" asp-switch-text="是|否"></cl-switch>
        </div>
        <div class="layui-form-item">
            <label for="remark" class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <textarea id="remark" name="remark" placeholder="请输入内容" class="layui-textarea" maxlength="128">@ViewData.Model.Remark</textarea>
            </div>
        </div>
        <div class="layui-form-item layui-right">
            <button class="layui-btn" lay-submit lay-filter="confirm">确定</button>
        </div>
    </form>
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <script type="text/javascript" src="~/js/submit.js?_=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>
    <script type="text/javascript" src="~/js/verify.js"></script>
    <script>
        registerSubmit('Manager')
    </script>
</body>
</html>

Henxun.Cms.Admin/Views/Manager/EditUser.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@addTagHelper *,Henxun.Cms.Admin
@model Henxun.Cms.ViewModels.ManagerAddOrModifyModel
@{
    Layout = null;
    var roleList = ViewBag.RoleList as IEnumerable<SelectListItem>;
}
<html>
<head>
    <link rel="stylesheet" href="~/layui/css/layui.css" media="all" />
    <link rel="stylesheet" href="~/css/public.css" media="all" />
</head>
<body style="padding:10px">
    <form id="addUser" class="layui-form">
        @Html.AntiForgeryToken()
        <div class="layui-form-item layui-hide">
            @Html.LabelFor(m => m.Id, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.Id, new { Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.UserName, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.UserName, new { Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.RoleId, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.DropDownListFor(m => m.RoleId, roleList)
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.NickName, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.NickName, new { Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.Email, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.Email, new { Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.Mobile, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.EditorFor(m => m.Mobile, new { @type = "number", Class = "layui-input" })
            </div>
        </div>
        <div class="layui-form-item">
            @Html.LabelFor(m => m.IsLock, new { Class = "layui-form-label" })
            <cl-switch asp-for="IsLock" asp-switch-text="是|否"></cl-switch>
            @*@Html.LabelFor(m => m.IsLock, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.CheckBoxFor(m => m.IsLock, new String("lay-skin='switch' lay-filter='switchTest lay-Text='是|否'"))
            </div>*@
        </div>
        <div class="layui-form-item layui-form-text">
            @Html.LabelFor(m => m.Remark, new { Class = "layui-form-label" })
            <div class="layui-input-block">
                @Html.TextAreaFor(m => m.Remark, new { @placeholder = "请输入内容", Class = "layui-textarea" })
            </div>
        </div>
        <div class="layui-form-item layui-right">
            <button class="layui-btn" lay-submit lay-filter="addUser">确定</button>
        </div>
    </form>
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <script>
        layui.use(['form', 'jquery'], function () {
            var form = layui.form, $ = layui.jquery;
            form.on('submit(addUser)', function (data) {

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "/Manager/Edited",
                    data: data.field,
                    success: function (result) {
                        layer.msg(result.msg, { icon: 6, area: ['450px', ''], shade: [0.5, '#000', true] });
                        var index = parent.layer.getFrameIndex(window.name);
                        parent.layer.close(index);//关闭弹出的子页面窗口
                        window.parent.location.reload();//写在这里的话是只有提交成功了才刷新那个页面 
                    },
                    error: function () {
                        layer.msg(result.msg, { icon: 2, area: ['450px', ''], shade: [0.5, '#000', true] });
                    }
                })
            })
        })
    </script>
</body>
</html>

Henxun.Cms.Admin/Views/Manager/ManagerInfo.cshtml
@model Henxun.Cms.Models.Manager
@{
    ViewData["Title"] = "个人信息";
}
<form class="layui-form layui-row">
    <div class="layui-col-md3 layui-col-xs12 user_right">
        <div class="layui-upload-list">
            <img src="@Model.Avatar" class="layui-upload-img layui-circle userFaceBtn userAvatar" id="userFace">
        </div>
        <button type="button" class="layui-btn layui-btn-primary userFaceBtn"><i class="layui-icon">&#xe67c;</i> 掐指一算，我要换一个头像了</button>
        @Html.Hidden("Avatar", Model.Avatar)
        @Html.Hidden("Id", Model.Id)
        @Html.AntiForgeryToken()
    </div>
    <div class="layui-col-md6 layui-col-xs12">
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">用户账号</label>
            <div class="layui-input-block">
                <input type="text" value="@Model.UserName" name="UserName" ,id="UserName" disabled class="layui-input layui-disabled">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">用户角色</label>
            <div class="layui-input-block">
                <input type="text" value="@Model.RoleName" name="RoleName" id="RoleName" disabled class="layui-input layui-disabled">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">真实姓名</label>
            <div class="layui-input-block">
                <input type="text" value="@Model.NickName" name="NickName" id="NickName" placeholder="请输入真实姓名" lay-verify="required" class="layui-input realName">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">手机号码</label>
            <div class="layui-input-block">
                <input type="tel" value="@Model.Mobile" name="Mobile" id="Mobile" placeholder="请输入手机号码" lay-verify="phone" class="layui-input userPhone">
            </div>
        </div>
        <div class="layui-form-item" pane="">
            <label class="layui-form-label">电子邮箱</label>
            <div class="layui-input-block">
                <input type="tel" value="@Model.Email" name="Email" id="Email" placeholder="请输入电子邮箱" lay-verify="email" class="layui-input userPhone">
            </div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label">备注</label>
            <div class="layui-input-block">
                <textarea placeholder="请输入内容" name="Remark" id="Remark" class="layui-textarea myself">@Model.Remark</textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <button class="layui-btn" lay-submit="" lay-filter="changeManager">立即提交</button>
                <button type="reset" class="layui-btn layui-btn-primary">重置</button>
            </div>
        </div>
    </div>
</form>
@section Scripts{
    <script type="text/javascript" src="~/layui/layui.js"></script>
    <script type="text/javascript" src="~/js/manager/managerInfo.js?_=@DateTime.Now.ToString("yyyyMMddHHmmss")"></script>
}